version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "splunk-aws-cloudwatch-streaming-metrics-processor"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-123egwcg3o3qx"
s3_prefix = "splunk-aws-cloudwatch-streaming-metrics-processor"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

