AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  splunk-aws-cloudwatch-streaming-metrics-processor

  Sample SAM Template for splunk-aws-cloudwatch-streaming-metrics-processor

Globals:
  Function:
    Timeout: 60

Resources:
  SplunkAWSCloudWatchStreamingMetricsProcessor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: main/
      Handler: app.lambda_handler
      Runtime: python3.8
